RestaurantBookingWeb/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Mvc;

using RestaurantBooking.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace RestaurantBookingWeb.Controllers
{
    public class ReservationController : Controller
    {
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly IConfiguration _configuration;
        private static HttpClient client = new HttpClient();

        private string apiPath = "";
        public ReservationController(IConfiguration configuration, IWebHostEnvironment _env)
        {
            webHostEnvironment = _env;
            _configuration = configuration;

            apiPath = _configuration["ReservationAPI"];
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<Reservation> reservations = null;

            HttpResponseMessage response =  await client.GetAsync(apiPath);

            if (response.IsSuccessStatusCode)
            {
                reservations = await response.Content.ReadFromJsonAsync<IEnumerable<Reservation>>();
            }


            return View(reservations);
        }

        //GET
        public async Task<IActionResult> Upsert(int? id)
        {
            Reservation reservation = new();

            if (id == null || id == 0)
            {
                //Create Reservation
                return View(reservation);
            }
            else
            {
                //Edit Reservation
                HttpResponseMessage response = await client.GetAsync(apiPath + id.ToString());

                if (response.IsSuccessStatusCode)
                {
                    reservation = await response.Content.ReadFromJsonAsync<Reservation>();
                }
                else
                {
                    TempData["error"] = "Error getting this reservation.";

                    return RedirectToAction("Index");
                }
            }
            return View(reservation);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Reservation reservation)
        {

            if (ModelState.IsValid)
            {

                // Create New
                if (reservation.Id == 0)
                {
                    HttpResponseMessage response = await client.PostAsJsonAsync(apiPath, reservation);
                    response.EnsureSuccessStatusCode();

                    if (response.IsSuccessStatusCode)
                        TempData["success"] = "Reservation created successfully.";
                    else
                    {
                        TempData["error"] = "Error creating reservation.";
                        return View(reservation);
                    }
                }
                else
                {
                    HttpResponseMessage response = await client.PutAsJsonAsync(apiPath + reservation.Id, reservation);
                    response.EnsureSuccessStatusCode();

                    if (response.IsSuccessStatusCode)
                        TempData["success"] = "Reservation updated successfully.";
                    else
                    {
                        TempData["error"] = "Error updating reservation.";
                        return View(reservation);
                    }
                }

                return RedirectToAction("Index");
            }

            return View(reservation);
            
        }

        // GET
        // This is to Confirm
        public async Task<IActionResult> Delete(int? id)
        {
            Reservation reservation = new();

            HttpResponseMessage response = await client.GetAsync(apiPath + id.ToString());

            if (response.IsSuccessStatusCode)
            {
                reservation = await response.Content.ReadFromJsonAsync<Reservation>();

                return View(reservation);
            }

            return NotFound();

        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(int? id)
        {
            // Consume API
            HttpResponseMessage response = await client.DeleteAsync(apiPath + id.ToString());

            if (response.IsSuccessStatusCode)
            {
                TempData["success"] = "Reservation cancelled successfully.";
            }
            else
            {
                TempData["error"] = "Error cancelling reservation.";
            }

            return RedirectToAction("Index");
            
        }

        
    }

}

RestaurantBookingWeb/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;

using RestaurantBooking.Models;
using RestaurantBooking.Models.ViewModel;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace RestaurantBookingWeb.Controllers
{
    public class SearchController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IConfiguration _configuration;
        private static HttpClient client = new HttpClient();

        private string apiPath = "";

        public SearchController(IConfiguration configuration, IWebHostEnvironment webHostingEnv)
        {
            _webHostEnvironment = webHostingEnv;
            _configuration = configuration;

            apiPath = _configuration["ReservationAPI"];
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            SearchReservationVM searchVM = new SearchReservationVM();

            HttpResponseMessage response = await client.GetAsync(apiPath);

            if (response.IsSuccessStatusCode)
            {
                searchVM.SearchResult = await response.Content.ReadFromJsonAsync<IEnumerable<Reservation>>();
            }

            return View(searchVM);
        }

        [HttpPost]
        [ActionName("Index")]
        public async Task<IActionResult> IndexPOST(SearchReservationVM searchVM)
        {
            HttpResponseMessage response = null;

            if (searchVM.SearchDate)
            {
                response = await client.GetAsync(apiPath + "bydate/" + searchVM.DateFilter.ToString("dd-MM-yyyy"));
            }
            else
            {
                response = await client.GetAsync(apiPath + "byphone/" + searchVM.PhoneNumber);
            }

            if (response.IsSuccessStatusCode)
            {
                searchVM.SearchResult = await response.Content.ReadFromJsonAsync<IEnumerable<Reservation>>();
            }

            return View(searchVM);
        }

        

       
    }

}

RestaurantBookingWeb/Views/Reservation/Delete.cshtml
@model Reservation

@{
    ViewData["Title"] = "Cancel Reservation";
}

<form method="post" asp-action="Delete">

<div class="border p-3 mt-4 row">
    <div class="row pb-2">
        <h2 class="text-primary">Cancel Reservation</h2>
        <hr />
    </div>
    <div asp-validation-summary="All"></div>
    <input asp-for="Id" hidden />
    <input asp-for="TableNumber" hidden />
    <div class="mb-3">
        <label asp-for="GuestName"></label>
        <input asp-for="GuestName" class="form-control" disabled />
        <span asp-validation-for="GuestName" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="GuestPhone"></label>
        <input asp-for="GuestPhone" rows="3" class="form-control" disabled></input>
        <span asp-validation-for="GuestPhone" class="text-danger"></span>
    </div>

    <div class="mb-3 col-6">
        <label asp-for="ReservationTime"></label>
        <input type="text" class="form-control" disabled value="@(Model.ReservationTime.ToString("dd/MM/yyyy HH:mm tt"))"/ >
        <span asp-validation-for="ReservationTime" class="text-danger"></span>
    </div>
    <div class="mb-3 col-6">
        <label asp-for="DurationMinute"></label>
        <input asp-for="DurationMinute" class="form-control" disabled />
        <span asp-validation-for="DurationMinute" class="text-danger"></span>
    </div>
    
    <div class="mb-3 col-12">

        <button type="submit" class="btn btn-danger" style="width:150px">Cancel</button>
        <a asp-controller="Reservation" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
    </div>
</div>

</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

RestaurantBookingWeb/Views/Reservation/Index.cshtml
@model IEnumerable<Reservation>
@{
    ViewData["Title"] = "Reservation List";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Reservation List</h2>
        </div>
        <div class="col-6 text-end">
            <a class="btn btn-primary" asp-controller="Reservation" asp-action="Upsert">
               <i class="bi bi-plus-circle"></i> &nbsp; New Reservation
            </a>
            <a class="btn btn-primary" asp-controller="Search" asp-action="Index">
               <i class="bi bi-search"></i> &nbsp; Search
            </a>

        </div>
    </div>
    <br />
    <br />

<table id="tblData" class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Reservation Date/Time
            </th>
            <th>
                Table Number
            </th>
            <th>
                Guest Name
            </th>
            <th>
                Guest Phone
            </th>
            <th>
                Duration
            </th>
            <th>
                
            </th>
        </tr>
    </thead>
    
    <tbody>
            @foreach(Reservation r in Model)
            {
                <tr>
                    <td>
                        @r.ReservationTime.ToString("dd/MM/yyyy HH:mm tt")
                    </td>
                    <td>
                        @r.TableNumber
                    </td>
                    <td>
                        @r.GuestName
                    </td>
                    <td>
                        @r.GuestPhone
                    </td>
                    <td>
                        @r.DurationMinute Mins
                    </td>
                    <td>
                        <div class="w-75 btn-group text-center" role="group">
                        <a asp-controller="Reservation" asp-action="Upsert" asp-route-id="@r.Id" class="btn btn-primary mx-2">
                            <i class="bi bi-pencil-square"></i> Change
                        </a> 
                        <a asp-controller="Reservation" asp-action="Delete" asp-route-id="@r.Id" class="btn btn-danger mx-2">
                            <i class="bi bi-trash-fill"></i> Cancel
                        </a> 
                    </div>
                    </td>

                </tr>
            }
        </tbody>
</table>
</div>

RestaurantBookingWeb/Views/Reservation/Upsert.cshtml
@model Reservation

@{
    ViewData["Title"] = (Model.Id != 0 ? "Change" : "New") + " Reservation";
}

<form method="post" asp-action="Upsert" enctype="multipart/form-data">

<div class="border p-3 mt-4 row">
    <div class="row pb-2">
        <h2 class="text-primary">@(Model.Id != 0 ? "Change" : "New") Reservation</h2>
        <hr />
    </div>
    <div asp-validation-summary="All"></div>
    <input asp-for="Id" hidden />
    <input asp-for="TableNumber" hidden />
    <div class="mb-3">
        <label asp-for="GuestName"></label>
        <input asp-for="GuestName" class="form-control" />
        <span asp-validation-for="GuestName" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="GuestPhone"></label>
        <input asp-for="GuestPhone" rows="3" class="form-control"></input>
        <span asp-validation-for="GuestPhone" class="text-danger"></span>
    </div>

    <div class="mb-3 col-6">
        <label asp-for="ReservationTime"></label>
        <input asp-for="ReservationTime" class="form-control" asp-format="{0:yyyy-MM-ddTHH:mm}" />
        <span asp-validation-for="ReservationTime" class="text-danger"></span>
    </div>
    <div class="mb-3 col-6">
        <label asp-for="DurationMinute"></label>
        <input asp-for="DurationMinute" class="form-control" disabled />
        <span asp-validation-for="DurationMinute" class="text-danger"></span>
    </div>
    
    <div class="mb-3 col-12">
        @if (Model.Id != 0)
            {
                <button type="submit" class="btn btn-primary" style="width:150px">Change</button>
            }
            else
            {
                <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
            }
        <a asp-controller="Reservation" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
    </div>
</div>

</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

RestaurantBookingWeb/Views/Search/Index.cshtml
@model SearchReservationVM
@{
    ViewData["Title"] = "Search Reservation";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Search Reservation</h2>
        </div>
    </div>
    <form method="post" asp-controller="Search" asp-action="Index">
    <div class="row pt-4">
        
        <div class="col-6">
            <label asp-for="PhoneNumber"></label>
            <input asp-for="PhoneNumber" class="form-control" /> 
            <button type="submit" class="btn btn-primary" style="width:150px"><i class="bi bi-search"></i>&nbsp;Search</button>
         </div>
         <div class="col-6">
             <input type="checkbox" asp-for="SearchDate" id="SearchDate" name="SearchDate" class="d-none"/>
             <label asp-for="DateFilter"></label>
             <input asp-for="DateFilter" class="form-control" />
             <button type="submit" onclick="$('#SearchDate').prop('checked', true);" class="btn btn-primary" style="width:150px"><i class="bi bi-search"></i>&nbsp; Search</button>
        </div>
        
     </div>
     </form>
    <br />
    <br />

<table id="tblData" class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Reservation Date/Time
            </th>
            <th>
                Table Number
            </th>
            <th>
                Guest Name
            </th>
            <th>
                Guest Phone
            </th>
            <th>
                Duration
            </th>
            <th>
                
            </th>
        </tr>
    </thead>
    
    <tbody>
            @if (Model.SearchResult != null)
                foreach(Reservation r in Model.SearchResult)
                {
                    <tr>
                        <td>
                            @r.ReservationTime.ToString("dd/MM/yyyy HH:mm tt")
                        </td>
                        <td>
                            @r.TableNumber
                        </td>
                        <td>
                            @r.GuestName
                        </td>
                        <td>
                            @r.GuestPhone
                        </td>
                        <td>
                            @r.DurationMinute Mins
                        </td>
                        <td>
                            <div class="w-75 btn-group text-center" role="group">
                            <a asp-controller="Reservation" asp-action="Upsert" asp-route-id="@r.Id" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil-square"></i> Change
                            </a> 
                            <a asp-controller="Reservation" asp-action="Delete" asp-route-id="@r.Id" class="btn btn-danger mx-2">
                                <i class="bi bi-trash-fill"></i> Cancel
                            </a> 
                        </div>
                        </td>

                        </tr>
                    }
                else
                {
                    <tr>
                        <td colspan="6">
                            No Result Found
                        </td>
                    </tr>
                }
        </tbody>
</table>
</div>

RestaurantBookingWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - My Restaurant</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootstrapwatch.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="~/RestaurantBookingWeb.styles.css" asp-append-version="true" />
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <div class="container-fluid">
            <a class="navbar-brand" asp-controller="Reservation" asp-action="Index">Reservation</a>
            <button class="navbar-toggler"  type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor02">
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                  <a class="nav-link" asp-controller="Reservation" asp-action="Index">Reservation
                    <span class="visually-hidden">(current)</span>
                  </a>
                </li>
              </ul>
              
            </div>
          </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container">
            &copy; 2022 - My Restaurant Reservation - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RestaurantBookingWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script type="text/javascript">
        $(document).ready(function () {
            toastr.success('@TempData["success"]')
        });
        
    </script>
}
@if(TempData["error"] != null)
{
    <script type="text/javascript">
        $(document).ready(function () {
            toastr.success('@TempData["error"]')
        }
    </script>
}